### ISSUE TITLE
Dependency format has changed

### ISSUE THREAD

**Issue by wighawag** [HaxeFoundation/haxelib#157]
Hi got this error when trying to publish library using the new version of haxelib.
I saw that now haxelib accept an array of dependencies
Could haxelib accept both version  (at least for a transition period ?)

**Comment by jgranick** [comment]
I just got this error using the latest version on a Windows machine (where `haxelib selfupdate` does work). Most of my libraries use an empty `"dependencies": {}`, which failed

**Comment by back2dos** [comment]
This is really weird. What haxelib version did you get? The code that raised this error message was removed [is nowhere to be found anymore](https://github.com/HaxeFoundation/haxelib/search?q=format+has+changed&type=Code&utf8=%E2%9C%93),

**Comment by jgranick** [comment]
Hmm, perhaps I actually got the error on Linux, then I probably tried removing the "dependencies" field entirely to submit, but I left a trailing comma after the field before it, which resulted in a cryptic error about "position 315" or something. I wanted to report the problem I had, but perhaps I did not try to resubmit with the dependencies field as-is, because I expected the same error

**Comment by jgranick** [comment]
Sorry if this sounds like a false alarm, just trying to bring attention to things and not forget them as they come up
