### ISSUE TITLE
Error when attempting to use ~/.haxelib/ as library directory

### ISSUE THREAD

**Issue by lostfictions** [HaxeFoundation/haxelib#161]
When running `haxelib setup`, if you try to use `~/.haxelib/` as the path to the local repository, it will fail with the ambiguous error `Is a directory.` What's more, trying to run `haxelib setup` again and choosing a different directory will fail until `~/.haxelib/` is removed.

If I had to guess, I'd say [`getRepository` in Main.hx](https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Main.hx#L731) isn't handling the case where `.haxelib` is a directory, which I guess is a pretty simple fix.

At a higher level, though, forbidding the use of `~/.haxelib` as a repository path strikes me as unexpected behaviour. Most package managers I know of actually default to a similar convention: `npm` saves packages to `~/.npm`, `cabal` saves to `~/.cabal`, `gem` has `~/.gem`, `cargo` is `~/.cargo`, etc. I think it would make sense if haxelib permitted following suit. I'm not sure how doable that is given the established convention, though.

**Comment by back2dos** [comment]
Just so that I understand: What you want is that if `~/.haxelib` is a directory, it should be assumed to simply be the directory? That would be doable, but with that configuration, a subsequent `haxelib setup` would become impossible.

Also I would point out that npm saves modules into `node_modules`. By that I just mean to say that this is not as universal a convention as you make it sound.

For your immediate needs, setting the `HAXELIB_PATH` environment variable to `~/.haxelib` should also simply do what you are after, as [that has absolute priority](https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Main.hx#L728).

**Comment by fzzr-** [comment]
Wrong place. You need move this issue to https://github.com/TiVo/intellij-haxe/issues

**Comment by lostfictions** [comment]
Uh, no I don't? Not sure where you got the idea, but this has nothing to do with IntelliJ. I don't use it, and I didn't mention it here.

@back2dos: fair enough! I guess it doesn't make sense to enable the use of `~/.haxelib` as a directory given that constraint. Still, `haxelib setup` should probably handle the case of `~/.haxelib` being a preexisting directory or of a user trying to set it as the repository path, as I did by happenstance a few days ago before I realized it wasn't valid.

**Comment by ncannasse** [comment]
We should test that case in setup and give a proper error message

**Comment by TheHippo** [comment]
This is the output you get when trying to set haxelib to `~/.haxelib`. It's pretty confusing.

	hippo@hippo:~$ haxelib install lime
	This is the first time you are runing haxelib. Please run `haxelib setup` first
	hippo@hippo:~$ haxelib setup
	Please enter haxelib repository path with write access
	Hit enter for default (/usr/lib/haxe/lib)
	Path : /home/hippo/.haxelib/
	[file_open,/home/hippo/.haxelib]
	hippo@hippo:~$ haxelib install lime
	This is the first time you are runing haxelib. Please run `haxelib setup` first

**Comment by TheHippo** [comment]
@back2dos: setting the `HAXELIB_PATH` environment variable does not help. (Linux)

**Comment by TheHippo** [comment]
npm saves its cache to `.npm`, gem some information about the remote server into `.gem`. 

What about if `~/.haxelib/` is folder the `.haxelib` file is saved under `~/.haxelib/haxelib` and otherwise under `~/.haxelib`? This doesn't make that much sense but provide the most convience for Linux users and still be compatible with haxelib (changing the directory is still possible, etc.)

**Comment by back2dos** [comment]
That seems like a workable solution.

**Comment by ncannasse** [comment]
We have code looking for .haxelib file in the haxe compiler for runtime NDLL loading, please simply forbid .haxelib as a directory

**Comment by ibilon** [comment]
@ncannasse why is that?

I tried to look into the haxe repository and found genneko.ml but the ocaml prevented me from understanding.

I fail to see why you need haxelib to load ndll.

**Comment by ncannasse** [comment]
Because in case the NDLLs are not in the local exe directory, it will use the currently installed lib path to load them

**Comment by ibilon** [comment]
Putting aside this feature, which imo is a hack for developers, since user have neither haxelib nor the library, so the build code should really just copy the ndlls to not make a difference between dev and deploy.

Why not go through haxelib? `-lib` does-it and it'd avoid blocking changes in haxelib.

**Comment by jakwings** [comment]
It is a bad file name. Why not change the name from `.haxelib` to `.haxe.conf` or the like? It just wasted my time.

**Comment by nadako** [comment]
I added the check that protects against setting haxelib repo to `~/.haxelib` for now, but what we should do with this issue anyway? The [code in `genneko.ml`](https://github.com/HaxeFoundation/haxe/blob/ed83390bc344f247f8c63d085e1853257947f3c9/genneko.ml#L687-L698) looks quite weird indeed (for example, it uses hardcoded path on Windows, but tries to read `$HOME/.haxelib` on other OS), so I think [@ibilon's last comment](https://github.com/HaxeFoundation/haxelib/issues/161#issuecomment-110645361) is quite correct.

Assigning this to @ncannasse.

**Comment by ncannasse** [comment]
I don't think we should remove the runtime resolving of libraries using haxelib configuration.
We could change .haxelib by .haxelibconfig but that would cause a lot of mess for people that have already a config set. I still think that giving the proper error messages is the best way to deal with this.

**Comment by nadako** [comment]
Okay, let's close it for now then.

**Comment by ncannasse** [comment]
@nadako did you add proper error messages when trying to save .haxelib and it's a directory ?

**Comment by nadako** [comment]
@ncannasse I did this 513d2acf633bf9d1118b8b327675f6862e8b3ce4

**Comment by Fintan** [comment]
I just installed haxe and haxelib on my Mac and I get the same error message (This is the first time you are runing haxelib. Please run `haxelib setup` first) as described above when setting location to ~/.haxelib

**Comment by nadako** [comment]
Yeah, the fix is not yet released.

**Comment by Fintan** [comment]
ah ok thanks

**Comment by oxitech239** [comment]
This problem appears to persist upto today for haxelib 3.3.0
