### ISSUE TITLE
`haxelib install` should not install dependencies if they exist as a "dev" or "git" library already

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxelib#174]
When you run `haxelib install`, dependencies are installed, even if they already exist.

For example, if you have OpenFL and Lime set up as `haxelib dev` directories, installing HaxeFlixel will force the download of both libraries before finishing the install.

**Comment by ncannasse** [comment]
Oh, that's because we assume that "dev" is outdated. That should not be the case for dependencies indeed, unless the version number is explicitly required in the dependency

**Comment by nadako** [comment]
This is now fixed thanks to @ibilon, however note that we want to lose `dev`-mode for git/hg installs (see #263 and #238), which means that it'll probably "consider vcs checkouts it as outdated" again at some point. This is probably correct however, because we also want to implement multiple vcs checkouts support (see #238).
