### ISSUE TITLE
haxelib submit fails due to limited license choices

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/haxelib#178]
We have a haxelib that we'd like to publish, and its license is Apache 2.0.  This is an open source license, but the haxelib program refuses to allow this haxelib to be published because it's not one of the following licenses:

GPL,LGPL,BSD,Public,MIT

I think that the haxelib program should allow other licenses.  Perhaps a free form string for specifying the license.

**Comment by andyli** [comment]
FYI Apache has been added recently (#155). We need to wait for a new haxelib release before using it though.

**Comment by back2dos** [comment]
We have rejected the notion of free form strings a while ago.
However, if you make a solid case for any particular license, we'll be glad to add it. As Andy said, Apache license has been added just recently and should become available to you in the days to come.

**Comment by ncannasse** [comment]
@back2dos could you confirm that Apache is correctly accepted as license string now ? @jasononeil  the website might need to be updated in order to allow such submit

**Comment by bjitivo** [comment]
The website still is not accepting Apache license haxelibs as of about 1 minute ago, I tried it ...

**Comment by ncannasse** [comment]
@jasononeil up :)

**Comment by back2dos** [comment]
It's a matter of recompiling the server. I just don't have my haxe.org access on this machine, but I can take care of it tomorrow evening, if Jason doesn't beat me to it ;)

**Comment by back2dos** [comment]
Ok, new server version is online, with Apache License support.

**Comment by bjitivo** [comment]
I don't see how change 68f25d9 fixes this issue.  That change does not allow the user to specify Apache as the license, the haxelib program will reject it.  See the LICENSES variable in Data.hx.

**Comment by back2dos** [comment]
It doesn't. That was a mere flip (the commit should have been referring to 187). This ticket as a duplicate of #155, which was closed by https://github.com/HaxeFoundation/haxelib/commit/5b0951509729d30b7a11a2aa6155408f7e6be360

There also is no LICENCES variable in Data.hx [or elsewhere](https://github.com/HaxeFoundation/haxelib/search?q=licences&type=Code&utf8=%E2%9C%93) since quite a while, so the issue you are experiencing must be with having an outdated haxelib version.

This has been implemented, deployed and tested. If it still fails on your end, please provide more detailed information.

**Comment by bjitivo** [comment]
Yeah, I have an outdated version of haxelib here.  I had hacked it to add Apache to the LICENSES list, and assumed that you'd have to do the same here, but I guess the code has changed like you said and I didn't realize it.  Thanks.
