### ISSUE TITLE
Should 'haxelib upgrade mylib' work the same as 'haxelib update mylib'?

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxelib#188]
I cannot remember how many times this has happened:

`haxelib upgrade mylib`

I'm thinking I want to update only the one library, but instead it upgrades everything. There's the separate `update` command for this, but the difference seems a little too nuanced to me.

Is there a good reason why they can't be synonyms, and behave differently based on the number of arguments?

**Comment by jasononeil** [comment]
+1, this has caught me out too.

**Comment by ncannasse** [comment]
agreed

**Comment by ibilon** [comment]
Then there's the question of how to present that.

We can't let both stay in the help if they are synonyms, it'd be confusing:
```
  Usage: haxelib [command] [options]
  Basic
    install   : install a given library, or all libraries from a hxml file
    upgrade   : upgrade a single or all installed libraries
    update    : does the same thing as the previous one
```
so which one to choose?

And then what to make of the other? Silently redirect to the chosen one? Fail with an error message saying "nop use the other"? Simply removing it?

Personally I'd choose the "Silently redirect to the chosen one" since otherwise it'd be annoying to the old users.

**Comment by nadako** [comment]
I added support `haxelib upgrade <libname>` that simply redirects to the update function, however I think that `update`/`upgrade` should indeed become synonyms, similar to NPM:
* `haxelib update/upgrade` - updates all installed libs
* `haxelib update/upgrade <libname>` - updates `libname`
If noone objects soon, I'll implement that :)

**Comment by nadako** [comment]
Oh, nevermind, @jgranick suggested exactly that and @ncannasse agreed, so I'm reworking it :-)
