### ISSUE TITLE
Decide whether depending on neko is fine.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxelib#204]
Given that `haxe --run` has a number of quirks (particularly macros not being supported), and the fact that the nightly builds for linux use neko based binaries, I wonder whether we still need to support it.

@ncannasse @Simn @waneck If there are still reasons to use `--run`, could you please explain?

**Comment by Simn** [comment]
I still don't know why --run even exists, it seems like a weaker version of --interp in every way.

**Comment by back2dos** [comment]
The reason is that there is no straight forward way to pass arguments to `--interp`. You can do `haxe --run TheClass <arg1> ... <argN>`, while the same is relatively quirky to achieve with `--interp` (using `-D` or `-c-arg`). Having an `--interp-args` that would just skip all following arguments and make those available through `Sys.args()` (as opposed to giving you the compiler arguments, which could still be done in the absence of `--interp-args`) would do the trick, I think.

**Comment by waneck** [comment]
I think that ideally we shouldn't depend on neko. The nightly builds don't
use --run because of some problems there was with selfupdate on this
context. I think once all these issues are settled, --run should be the
preferred way to use haxelib

**Comment by Simn** [comment]
Experimenting on the development branch (so we can get a build): https://github.com/HaxeFoundation/haxe/commit/ac89c25c9c1b6c5b3cc383a825e7fcac6542646c

Maybe that's all that's required?

**Comment by back2dos** [comment]
@waneck I don't get that. Having a precompiled binary is what breaks selfupdate in the first place :D

@Simn That looks like it could do the trick.

**Comment by waneck** [comment]
@back2dos, I recommend you to try it yourself. I don't remember anymore
what was wrong, but selfupdate did fail when running through --run

**Comment by ncannasse** [comment]
@Simn looks good

**Comment by jgranick** [comment]
In my experience, `haxe --run` is *significantly* slower than Neko binaries. Slowing down `haxelib path` and other operations will have a negative effect on Haxe-based builds. I feel like `haxe --run` is better as a fallback if a Neko binary is not present.

This is how I handled it in the shim.

Lime tools has a "-nocffi" flag, which it uses for certain operations (such as `lime rebuild`), which removes the binary dependency. This is not the default, though, because certain things just perform faster using (in Lime's case) CFFI.

**Comment by back2dos** [comment]
Personally, I lean towards neko, because honestly, without it you can't even do `haxelib run`, ergo you cannot use hxcpp, hxjava or hxcs without neko. Thus to me the neko dependency adversity seems rather academic.

Using neko increases speed as well as homogeneity and side steps a whole range of issues we've had with class path collisions and what not when haxelib is run with `haxe --run` in the wrong directories.

@ncannasse Can I please have an authoritative answer on this?

**Comment by andyli** [comment]
@jgranick Do you have a sample project that builds significantly slower using an interpreted haxelib? The amount of work done by haxelib should be pretty small comparing to the work by a C++ compiler...

**Comment by back2dos** [comment]
I would think the real difference in speed comes from the parsing and typing, rather than the execution.  If execution is a bottleneck, then because it is I/O-bound. The bigger haxelib gets, the more noticeable I think this will actually become. But then again, I think performance is the least of this project's issues.

**Comment by ncannasse** [comment]
On my windows box, using haxelib through --run gives me the following results (path haxelib path with dependencies resolution) :
```
Total time : 0.445s
------------------------------------
  filters : 0.000s, 0%
  macro execution : 0.327s, 73%
  other : 0.000s, 0%
  parsing : 0.115s, 26%
  typing : 0.003s, 1%
```

Running the same command from neko (with JIT) takes around 0.090s 

Are these extra 400ms an issue ? I guess it depends. If you are using compiler completion on a small project with no compiler cache, then it will impact your workflow since it will add to the time necessary to get back completion (and then 400ms is very slow). If you're doing that with compiler cache (as you should) then haxelib results are cached from the previous compilation so it's not called again.

But I agree with @back2dos, given that hxcpp and others depend on neko being installed, I guess it's still too early to entirely remove neko dependency, so if we have a solution that uses it it's fine.

One issue we had on Linux was when copying haxelib binary to /usr/bin it was striping the neko bytecode from it on some systems. We might want to still use a shim that uses `--run` on that platform

**Comment by waneck** [comment]
> One issue we had on Linux was when copying haxelib binary to /usr/bin it was striping the neko bytecode from it on some systems. We might want to still use a shim that uses --run on that platform

Can you elaborate on that? It seems very unlikely that a `cp` would strip the neko bytecode from it. Also I'd prefer we had a single solution for all platforms.

**Comment by ibilon** [comment]
Never heard a `cp` do that either,
but on some distribution of linux preload is enabled and that strip all neko executables, like haxelib.

**Comment by underscorediscovery** [comment]
> Are these extra 400ms an issue ? 

Yes.

When you need to call haxelib multiple times (because that is the nature of the tool commands) you will end up in 3 seconds time range before you have enough information to cache. And since the user can change flags any time, those can't be cached too aggressively. I'm not really sure how 400ms _doesn't_ sound like a problem, in what haxelib is for.

That's what @jgranick is getting at and I am of the same mind.

**Comment by hughsando** [comment]
Yes, 400ms is a big problem, since it is per haxelib used.
I agree that given "haxelib run" depends on neko, there is no extra practical dependency.

**Comment by Simn** [comment]
It looks like there's a consensus here, so I'll go ahead and close this issue. Personally I would prefer some separation between haxe, haxelib and neko, but I don't think we'll be able to lose neko anytime soon.
