### ISSUE TITLE
Second user in contributors can't submit.

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxelib#211]
Hi,

I'm trying to submit HaxePunk 2.5.4 but it isn't working for me,

in haxelib.json we have `"contributors": ["heardtheword", "_ibilon"],` and it was pushed to haxelib for the previous version (2.5.3, last in semver order).

But I get `User '_ibilon' is not a developer of project 'HaxePunk'`.

Is there anything else that should have been done or is it a bug?

**Comment by back2dos** [comment]
That is weird. Just tried it myself and it works. 

But apparently in your the database was not updated correctly, because according to the server you are not a contributor of HaxePunk: http://lib.haxe.org/u/_ibilon

Would you be so kind as to have the update be submitted by `heardtheword` to see if that updates you project list correctly?

**Comment by MattTuttle** [comment]
Submitted. I'm pretty sure we've done this in the past. Can you double check that `_ibilon` is listed as a contributor now?

**Comment by back2dos** [comment]
Nope. I've checked the code and this is quite a silly bug. Haxelib only considers the project changed if the number of developers changes: https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Repo.hx#L191

Since you are replacing "ibilon" with "_ibilon" the code assumes there are no changes. For now, can you please just resubmit (the same version) with `["heardtheword", "ibilon", "_ibilon"]` (and then follow up with `["heardtheword", "_ibilon"]` if you want to)?

**Comment by MattTuttle** [comment]
Done. Thanks for looking into this.
