### ISSUE TITLE
Featured haxelibs

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxelib#216]
I have drafted a first document here: https://github.com/HaxeFoundation/haxelib/wiki/Featured-haxelibs

Looking for some feedback!

@jasononeil @larsiusprime @hughsando @deltaluca @waneck @ncannasse @dpeek

**Comment by back2dos** [comment]
I think this is a bad time to open another can of worms ;)

Instead, I do think that it would be worth while to curate a list of competing libraries. The way that every other open source community does, e.g. [Go](https://github.com/avelino/awesome-go?utm_source=devmag.io), [nodejs](https://github.com/joyent/node/wiki/modules#table-of-contents) (to be fair that's from a time where the eco system was small enough for this to matter), ...

Surely, if there is enough time to actually decide which projects should die in favor of some alternatives, it should be easier to just list alternatives that reach a certain level of standard and make a not or two on the different approaches.

**Comment by deltaluca** [comment]
wrt "not redundant", I think it would be too difficult to keep strictly to this when there is not a clear favourite/"best" module.

**Comment by larsiusprime** [comment]
I think this in gernal is a good idea and a good implementation of the first spec.

The MAIN issue to watch out for community-wise is the perception (and reality) of getting into the game of "picking winners and losers" in the really subjective areas. 

Like picking a "featured bigass game framework" between Lime/OpenFL, NME, Luxe, Kha, etc, probably isn't a good quagmire to wade into.

That said, there are situations where you have this or that library that is super useful but people don't really know about it and it makes sense to give it more attention and let it become a standard.

So it might be important to emphasize that this isn't it just about focusing development by reducing fragmentation but also bringing more attention to such things.

**Comment by hughsando** [comment]
I think you could replace "not redundant" with "focused" (that is, not
monolithic).  So that would rule out these bigass game frameworks. Also,
featured libraries should probably only depend on other featured libraries.
Maybe a separate tag for frameworks - and here you could remove the
redundant clause, so you could simply feature them all, if they meet the
criteria.

I guess I might be confusing this with the concept of "installed by
default" libraries.  That is, the haxe installer pulls in these extra
libraries at install time.  This would encourage people to write code that
depends on an "default" library, and may also allow us to move some code
out of "std" into "default" libraries.  Default libraries would have to
work with updates to the compiler (ie, unit tested against the master
branch).  If, say, tink were installed by default, I think we would see a
wider adoption of macros.

**Comment by jasononeil** [comment]
Great start @Simn!  My thoughts:

- Add a requirement: *Must be used in at least $x production projects*. 

    Or possibly, *Must be used by at least $x separate developers / companies*.  Just to ensure it is useful for more than one person / purpose.

- Add a requirement: *Must have a place for community discussion*.  It could be Github, IRC, Gitter, Trello, Stack Overflow, a forum, whatever.  But a known place (and documented in the README) to ask questions, get support, request features etc.

- I agree with @hughsando that "focused" should be a requirement for "featured libraries".  Later we could perhaps have a separate "featured frameworks" that allows overlap / monolith type behaviour.

- The *Not Redundant* clause is a can of worms, I can see the value long term though.  Already we have some libraries that might otherwise qualify that are overlapping (promhx and tink_core come to mind).  It would be a shame if tink_core couldn't be included because promhx was, and then tink_macros couldn't be included, etc.

- I'm not convinced that installing them by default is needed.  Is this common place in other langauges / ecosystems?  I would have thought increased visibility would have been enough (on the main Haxe website, featured or highlighted on the haxelib website, blog posts, etc)

**Comment by underscorediscovery** [comment]
Encouraging good quality work and rewarding it with placement can be a good thing.

However, given the past behaviour regarding community efforts, and the above discussions around "relevance", I am put off by the idea of someone specifically deciding whether or not to support a community project based on their bias. It could do more harm than good.

In my opinion, you could support the efforts of the community and promote good work by having a curated list, which could be voted by the community and the whole list can be displayed - BUT - display it at random on each visit. 

```
//load from a featured list in categories 
var gamelibs = ['blah', 'bleh', 'boo', 'bar'];
display_up_to_count_picked_at_random(gamelibs, 2);
```

**Comment by markknol** [comment]
There are "popular haxelibs" on homepage now. 

If someone wants a nice challenge then he could improve it by making "popular libs this month/year", 
and make a actual algorithm that takes time in account (to also have a "new upcoming libs"). for now I consider this good-enough.
