### ISSUE TITLE
Fancy version strings cause trouble

### ISSUE THREAD

**Issue by RobDangerous** [HaxeFoundation/haxelib#232]
Uploaded two libs yesterday with a version string of "15.07.00" (kha and kha2d). Those are not working (downloading with haxelib gets you a small, corrupted zip, listing files gives a 404). Uploaded "15.7.1" versions a little later, those work fine.

**Comment by nadako** [comment]
I think that comes from inconsistent version number handling. The library is uploaded as `15.7.0`, but the corresponding file is still named as `15,07,00`. I believe that SemVer requires version numbers not to have leading zeroes, so since we're using SemVer, we should validate and forbid these "fancy version strings". Hope that's okay with you :)

**Comment by RobDangerous** [comment]
As long as we get an actual error message it's all ok for me.
