### ISSUE TITLE
[feature request] haxelib: allow store and resume partial downloads

### ISSUE THREAD

**Issue by pqyptixa** [HaxeFoundation/haxelib#240]
Please add support to haxelib for storing partial downloads and resuming the downloading process. Not everyone has a fast and stable internet connection all the time.
Thanks for your work.

**Comment by ncannasse** [comment]
You can directly download the packages from http://lib.haxe.org, your browser should support resuming.

**Comment by ibilon** [comment]
I had the experience to have to manually download a ruby package and all its recursive dependencies once and it was a huge chore.

It's not something a user should have to do just because of his internet connection.
(and aren't downloads still slow outside of Europe?)

@ncannasse Could you reconsider this issue?

**Comment by jakwings** [comment]
@ncannasse Hi, it is strange that the browser cannot show the file size and estimated time for download. Do you have such issue? I use Firefox, Safari, Chrome. Your server IP is 5.39.76.185.
