### ISSUE TITLE
haxelib post submit version

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxelib#243]
After submitting the "format 3.2.0" library, I got the following message:
```
Version 3.2.0-alpha (id#3173) added
```
The `alpha` should not be there (most likely a default value that is not reset)

**Comment by nadako** [comment]
I'm only getting to know haxelib code base, but I think this is caused by 6d41c431e4d3056d4a8269c4aedc46acb408cafe - the `@:nullable` metadata is not supported by standard Haxe `RecordMacros`, so it thinks that it's not nullable and probably is converted to 0 and thus first constructor of the `Preview` enum. I guess that RecordMacros now supports `SNull<SEnum<...>>`, so I fixed it in 4548df2d601547d8c97aa4eb63b822d0a2855d21 and it looks good now. @back2dos please confirm/review

**Comment by nadako** [comment]
This is probably related: https://github.com/HaxeFoundation/haxe/commit/784efa790c11d17d604955b5221c530ced2a8804
