### ISSUE TITLE
possible security issue: html not escaped/filtered in haxelib release notes

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxelib#255]
Just look at current "recently updated" list:
![](http://take.ms/GLKgO)
There's an `<input type="file">` in release notes that is not escaped and rendered as is.

**Comment by Simn** [comment]
@jasononeil: This should be addressed.

**Comment by jasononeil** [comment]
I've just fixed most of the possible problems.  It was using the erazor template library, which has `Template` and `HtmlTemplate`, which does automatic escaping.  It's my mistake for picking the wrong one :/

There remains a vulnerability with the READMEs, I'm looking into it now...

**Comment by jasononeil** [comment]
I've added a ContentSecurityPolicy header to the haxelib site.  So you can still use HTML in your readme, and embed your travis images or tables or whatever, but it should prevent you from running custom JS or otherwise being malicious.

Everywhere else should now use escaped HTML.

Please let me know if any further security holes are found, or if the changes I've made have broken any project pages.  Hopefully not!
