### ISSUE TITLE
legacyhaxelib.Site is not compiling

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxelib#257]
Subj. It says `Type not found : tools.haxedoc.HtmlPrinter`. I believe haxedoc was removed at some point, so maybe it's time to remove legacyhaxelib as well?

**Comment by back2dos** [comment]
The whole point of this was to support Haxe 2 + legacy haxelib clients and so long as it works (to my knowledge we didn't have to touch it once since we deployed it two and a half years ago) I see no particular reason to remove the legacy support in and on itself. Dealing with ancient legacy code is bad enough, so if we can make those poor souls suffer a bit less with virtually no effort, I think it's worthwhile.

It would be good to throw it out of this repo (for one thing it just pollutes autocompletion), but also to either tag the state where it last existed, or move it somewhere else. It just feels wrong to discard the source code of a running binary.

**Comment by nadako** [comment]
+1 on moving this to a separate repo and making sure it compiled and works with haxe 2.x there. I'll look into it.

**Comment by fzzr-** [comment]
( [tool here](https://code.google.com/p/haxe/source/browse/trunk/std/tools/haxedoc/) )

**Comment by nadako** [comment]
Oh, I see, so it was part of Haxe std, not Haxelib, thanks!

**Comment by andyli** [comment]
Not sure since when, but it was fixed.
