### ISSUE TITLE
Haxelib git breaks safe directive identifiers in other libraries.

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxelib#357]
using conditional compilation where the target library is a git repo and the library name is not a valid identifier means conditional blocks do not fire.

download, chmod if need-be, and execute  `./run.sh`

https://drive.google.com/open?id=0B50VBiFVmWNUZ1hnRW5qSmVfZjQ

**Comment by tobil4sk** [comment]
@0b1kn00b Just because it seems like you still regularly use Haxe, is there a chance you remember what was in the google drive file or you have another copy? x) I have attempted to address a similar problem to this but I wanted to make sure this one is actually fixed.

**Comment by 0b1kn00b** [comment]
I think that's what I was on about, couldn't tell you what happened to the drive link. Are you implementing the haxelib updates?

**Comment by 0b1kn00b** [comment]
iirc you may want to pay attention to `$` signs, them having made their way into node js package names.

**Comment by tobil4sk** [comment]
Yes, I've done some refactoring which makes the code a bit safer and makes it a bit easier to fix stuff like this. And thanks for the heads up about `$`.

If you don't have the file then the bug fix in the PR that linked to this should resolve it. It ensures that:
`haxelib git invalid-name#;' some://url` is not possible

As long as `haxelib.json` is not allowed to have invalid names for git libraries, then it should be fine, as the name in `haxelib.json` is used as the conditional compilation flag instead of the one the user gives (to allow for library aliases and case insensitivity).

**Comment by 0b1kn00b** [comment]
Yeah that's perfect. Thinking back now maybe the `$` thing was more on the side of  `dts2hx`.
