### ISSUE TITLE
Allow local paths in -lib command-line option

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxelib#377]
In my case I have a set of projects with a references to my own libraries (with dependencies). Local haxelib repo looks like a not good solution:
1. haxelib don't search for repo in parent folders (so I must copy `.haxelib` to every project);
2. links to my sources in `.dev` (inside `.haxelib`) are absolute and
3. must be finely maintained.

So, I think, `haxe -lib path_to_the_library` is a good solution...

**Comment by back2dos** [comment]
This should be a relatively small change in `path`. It's important to handle paths first and dependencies and named libs after them, otherwise if you have `-lib ./liba -lib ./libb` and `liba` depends on `libb` you're going to get a conflict between the `libb` from the haxelib repo and the one from the path.

**Comment by yar3333** [comment]
Now I think, what `-lib path_to_lib` feature is not intuitive and brings the unnecessary complexity to haxe. If nobody think else, I close this issue.
