### ISSUE TITLE
haxelib submit password input broken in Windows

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxelib#421]
On Windows, when haxelib asks for password when submitting a library, if user enter `abc`, it will somehow get `a b c `. I have no idea why yet but I suspect it is caused by some changes in recent Windows update.

The current workaround is to directly pass the password as the last argument, i.e. `haxelib submit path/to/lib.zip password`.

**Comment by back2dos** [comment]
Hmm. I've just tested it (the haxelib build that shipped with 4.0.0-preview.3) with:

- plain cmd
- plain PowerShell
- PowerShell in cmd
- PowerShell in VSCode
- cmd in PowerShell in VSCode

All of that with haxeshim in between - which is more likely to introduce the problem you're describing rather than fix it.

![keep-calm-it-works-on-my-machine](https://user-images.githubusercontent.com/509501/41022972-5f8b80b2-696b-11e8-9ef7-05d4a0a84400.png)

**Comment by andyli** [comment]
The issue was reported by @yar3333, and I reproduced it with Neko 2.2.0 on my Windows 10 machine (Windows 10 Pro version 1803, OS build 17134.48).

I've just found out that it happens to the Neko 2.2.0 (32-bit) binary, but not Neko 2.1.0 (32-bit)...

For the record, the Haxe 3.4.7 and 4.0.0-preview.3 Windows installers are bundled with Neko 2.1.0, so they are fine...

**Comment by ncannasse** [comment]
I have the same problem on my machine as well. This is very problematic... and yes it's suddenly broken without any reason

**Comment by ncannasse** [comment]
There's definitely something wrong with Neko build because on same terminal I get the error in Neko but not in HL (which is supposed to use the same C function I think?)

**Comment by Jens-G** [comment]
Same issue. Workaround works.
