### ISSUE TITLE
What happens if two dependencies need different versions of a transitive dependency?

### ISSUE THREAD

**Issue by jedwards1211** [HaxeFoundation/haxelib#500]
Seeing that Haxe modules use a Java-style global package namespace makes me concerned that we may be out of luck if dependency A depends on C 2.0.0 but dependency B depends on C 3.0.0.

Is there a solution for this?

**Comment by back2dos** [comment]
In such a case, you cannot use A and B in the same build. That's not even a haxelib problem, but one inherent to all types being global in Haxe.

The solution is to resolve the conflict by using conditional compilation to either make A forward compatible or B backward compatible, e.g.:

```haxe
package liba;

import libc.C;

class A {
  static public function foo() {
    #if (libc < 3) C.oldMethod() #else C.newMethod() #end;
  }
}
```

Or make adapters (which liba will use instead of calling into libc directly):

```haxe
package liba;

#if (libc < 3) 
  typedef C = libc.C;
#else
  abstract C(libc.C) {
    public inline function new() this = new libc.C();
    // put the remaining interface here
  }
#end
```

In some cases you may need the adapters to be full blown classes, but most of the time abstracts will do without adding runtime overhead.

For some platforms it's also reasonably simple to split the build into two parts, where one uses liba and the other libb, in such a way that the interface between the two parts is free of types from libc.

**Comment by jedwards1211** [comment]
@back2dos confirms my suspicions, since Java has the same problem AFAIK.
I don't guess Haxe has any plans to eventually implement a Node.js-like module system that doesn't have this problem?

**Comment by jedwards1211** [comment]
Also shouldn't package authors be advised to include the major version in the package name?  It's kind of the only way to proactively prevent dependency hell with a module system like this

**Comment by back2dos** [comment]
> I don't guess Haxe has any plans to eventually implement a Node.js-like module system that doesn't have this problem?

This "problem" is far more common than you make it seem. It is the case in C (and C++ and Objective-C, C#, Python, PHP, Ruby, ...). JavaScript's module system is the outlier here.

Achieving the same in Haxe poses quite a few challenges (especially since Haxe is targeting a lot of platforms that have types in a global namespace).

> Also shouldn't package authors be advised to include the major version in the package name? It's kind of the only way to proactively prevent dependency hell with a module system like this

The communities of many other languages seems to be able to cope with this, so let's not be so dramatic. If anything, Haxe's conditional compilation gives library authors an edge in maintaining compatibility with different major versions, not just for their dependencies, but also Haxe itself. That indeed requires more involvement, but it is certainly advisable. It not only mitigates the conflicts you speak of, but it does so in a way that avoids dumping multiple versions of the same lib into the generated output.

**Comment by jedwards1211** [comment]
Yeah I see what you mean about the compilation targets, since I've just started looking into using Haxe I had mistakenly assumed that my deps would get bundled together if I output to another language, rather than being usable in a modular fashion.

> The communities of many other languages seems to be able to cope with this

"Cope" would be a charitable way of putting some of the dependency hell I remember dealing with in Java/Maven...  Starting to work with JS felt like stepping into the future.

> It not only mitigates the conflicts you speak of

Well, I think there's one caveat.  If C was recently upgraded to version 3 and I need a recent version of B that must rely on some new feature in C v3, but no version of A that supports C v3 has been released, I'm still out of luck right until A is updated right?

**Comment by back2dos** [comment]
> Starting to work with JS felt like stepping into the future. I'm always hopeful for tools to enable flourishing, not just coping.

Allowing the inclusion of parallel dependency trees (imagine C has 50 other transitive dependencies as any "good" npm module has) in the build does not only solve problems, it basically shifts them from devs to end users.

Enabling library authors to deal with different build configuration (dependency versions, Haxe versions, target runtimes) via conditional compilation is not mere coping. It adds quite a lot of wiggle-room, without impacting build size or speed.

> If C was recently upgraded to version 3 and I need a recent version of B that must rely on some new feature in C v3, but no version of A that supports C v3 has been released, I'm still out of luck right until A is updated right?

Right. Although the primary role of major versions is not to add new features. It is to break or even remove existing ones, and that's precisely why in your scenario A needs to be updated for C@3. Adding features in major versions should be the exception (i.e. when a redesign is needed to make it even possible to add the feature).

----

That said, I don't think anybody would be strictly against this. But neither design nor implementation will be trivial and if you wish to pursue the matter, I would suggest going through [haxe-evolution](https://github.com/HaxeFoundation/haxe-evolution)

**Comment by jedwards1211** [comment]
> Adding features in major versions should be the exception

Another way of putting this though, B could need to use a feature added in C v3.1.0, while A hasn't even implemented support for C v3.0.0 yet.

**Comment by back2dos** [comment]
> B could need to use a feature added in C v3.1.0, while A hasn't even implemented support for C v3.0.0 yet.

We can spend the next weeks walking through various hypothetical scenarios, but I don't see that it really matters.

The fundamental limitation of the approach you suggest is that it breaks down when the conflicting dependency is part of the dependents' APIs:

```haxe
// libc@2.0.0
package libc;

interface Constraint<T> {
  function test(value:T):Bool;
}

// libc@3.0.0
package libc;

interface Constraint<T> {
  function matches(value:T):Bool;
}

// liba depending on libc@2.0.0
package liba;

class A {
  static public function foo(foo:Foo):libc.Constraint<String>;
}
// libb depending on libc@3.0.0
package libb;

class B {
  static public function bar(constraint:libc.Constraint<String>):Bar;
}
```

And boom, I can't pass constraints produced by liba to libb. In JavaScript it doesn't matter and if you're lucky the runtime types align just enough not to cause a crash. But that's hardly a solution to anything.

In a statically type language, this problem is immediately visible, as it should be. And it has further ramifications: in my own code that interfaces with both libs, how do I distinguish which version of `Constraint` I mean? 

Interestingly, Deno seems to have a solution for importing different versions of the same type into the same module. Suppose we did the same, in the end as users of both liba and libb we'd be tasked with writing all sorts of glue code to wrap Constraint@2 in a Constraint@3 and vice versa, at which point I have to ask if it wouldn't be saner to just make a PR against liba to support libc@2...3.

At the end of the day, if we can will any solution into existence, the one I would prefer would be for library authors (with the support of their communities) to leverage Haxe's conditional compilation to support major version ranges, instead of inflating build time and size. And the good news is that once there is an adapter for exposing libc@3 via libc@2 APIs, not only liba can use it, but in fact anyone who wishes to migrate from libc@2 to libc@3.

---

Still, if you can propose a solution that doesn't come with a whole lot of other problems (such as the one I mentioned above) and can be implemented with sane effort, chances are it gets built. Insisting that it's impossible to live without while not putting anything actionable on the table will most definitely lead nowhere (except perhaps frustration).

**Comment by jedwards1211** [comment]
I understand it seemed like I was insisting it's impossible to live with, really I was just looking for more acknowledgement that it's potentially a hassle, and supporting simultaneous dep versions can be easier to live with.

I know Node has downsides too, large amounts of code being one of them.  Things like your constraint example are a limitation of some Node libs (for example all components in a React tree have to use the same version of React).  I think it's impossible to support simultaneous versions and magically present the same object instance to library consumers, so it's not like any of us should expect that to be solvable.

Despite the disadvantages there have been plenty of cases where Node's advantages save me time (e.g. transitive dependencies on different lodash versions)

The idea of making PRs is not very satisfying to me because it can take more time and I've seen many PRs take a long time to get merged (over year for a simple PR to Apollo libs, for one of Sindre Sorhus' simple popular libraries I've been waiting a month).  The option then is install my own fork (also more time consuming than cases where installing multiple versions just works.) I wouldn't want to be up against that if I'm trying to add features to a company's product but keep anything from breaking.

The thing I don't know about is how much modification it would take to Haxe's resolution to support dep-specific transitive dependency versions placed in sub-haxe_libraries folder.

I don't imagine major blockers to output code though.  Haxe could append the version name to output minority-version packages like `libc__v2_0_0` which is a valid identifier/package name in the target languages I'm familiar with at least.

**Comment by jedwards1211** [comment]
Anyway, I realize I've gone on more than enough about this so I'll drop it.  It's wrong for me to assume without experience that things in Haxe would be as much of a pain as they were for me in Java since Java didn't have conditional compilation.
